---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1569388/public_html/varotex.id/varotextaiwan
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH